from functools import reduce

file = '../codon_table.txt'

def read_codon_table(file):
    with open(file, 'r') as f:
        data = f.read()
        data = data.replace('\n', ',').replace('      ', ',').replace('   ', ',')

    data = data.split(',')

    codon_dict = {item.split(' ')[0]:item.split(' ')[1] for item in data if item is not ''}

    return codon_dict

def aa_from_codons(codon_dict):
    aa_dict = {}
    for codon, aa in codon_dict.items():

        aa_dict.setdefault(aa, [])
        aa_dict[aa].append(codon)

    return aa_dict

codon_dict = read_codon_table(file)

aa_dict = aa_from_codons(codon_dict)

prob_dict = {aa:len(aa_dict[aa]) for aa in aa_dict}

print(prob_dict)

pep_str="MTNGLEDSCQFTAIRIDDWYFPWQHVNTWESYPSMFEIVLQSYGFAMVLVQVNPMIHNDIHRQIYARANWETHFTGRYWGRWFRDDYWRGAYTFEFFDKGHLALPEVLNRPINGMYSYRFMEAWFKCKYDPGRRVVPIMAQEMQELGVVPLGNHRWYPSCLIPKDLWRQWWNLLAKTWREVTWVWYSLGEDNTFANIHMFGGFFTINKWKCERQKIRTCNMQMCPPFVPKLADEDMAGGSFWWFDLWQIQELAQFPCPILCPCLAVKTLQHTMMYPTFWHIAGTFMQKDKRPSGKNDAYKRLIRSSQTYIKLSICHLDPQMTNWIVKRYKDSCMATYSDVPDTGEAAIKNTQSILMMQDMYVWLRGERIVMQAAGRTHFKAFGQDEWKQKERMMTHAFVHPVMGGVSKNRMYWVFRTNTYWCVVNKGLIARRYTCNKGSLSTGDYMHDFDSNINYRDGNVAILPKNYYFHWAATTFTQDYAFTNHYLCFEDPREHQCETNWPYPKRQSVYCYTVGANSCSKWRIAPMPKQRQYMCSCEWCVWGQLQEWDEENLPLMMPFPWRWQNMPESYQGGEDYTSHPWPWMHMEVSDFCPMGSGRRSGHAGGTSWYTQHKGEDNANLSTVRSSYGTFCWRCYEEELSAGCYNYKDHVMNRMCQWSFYWMRANEDLNAEYTNSVRYLLMMLYRKEGTHREKPQYGWEHCLHCWMYHGYHGSISFGAVRLLGHQRHSEHGYECHWGGASNEIWAFYSGDCWDYHLWFSWIKNDYCIDHTYFMDTLLKMYDIPGVRATWDRPFWWPLAWFMCWADGDSMGPFYNSCRMHAQHCAGHGQRDDPQEYTATSMRSPIINYGFWGEAKNYEFVPDVTFHVMTNYEPWVCITGFATGHNHVRNCHIHEEKWVPYRCSPRMYGCANEPYVSEQHQMAHQQDGACAWYKNNDFKIFTNKDYWAGHPPNPCFWLARKPCAVYIDCGWVQRKSIGIRCYMGPPMKNYLMQLVTMMT"
pep_list = list(pep_str) + ['Stop']

score = []
for aa in pep_list:
    score.append(prob_dict[aa])


reduce(lambda a1,a2: a1*a2 % 1000000, score)
