def count_ntides(dna_string):
    a_ct, c_ct, t_ct, g_ct, other_list = 0,0,0,0,0
    for n in dna_string:
        if n == 'A':
            a_ct +=1
        elif n == 'C':
            c_ct +=1
        elif n =='G':
            g_ct +=1
        elif n == 'T':
            t_ct +=1
        else:
            other_list+=1

    return a_ct, c_ct, g_ct, t_ct

As, Cs, Gs, Ts = count_ntides(
"TCGTTTCGCCGAAACGGGCCATTGACGTAGCTTCCGATGTAGTTTTTGTTGTGTGTTCCCACTTGACGCCCGAAATGCCATTAGTCACCAAGTGGAAGACTCAATCCGTGACTAGGTAACGCTGTTATGTGCGACCCGGTATGGTGATATATGACACGCGGTCGCGTATAGCGGCACACTACAACCGCGTTACGGTAGTACCTACCGTTACTGCGGTAAAGGATATCCAGGTTGGAAGTATTCTAGAACACAGCAAAGAGTTTTGTCCACCACAGGTCACAGGAGGGGGGCCGTTTAAATTCTCTAACTTGGTAAGCCGGTATAAATGGAAAGCAATCCTTAGTGAAACGCAGCGAACATACTGAGAGATGGGCTCTTTTTCGTACTCACTGTACTGGGTCCGGTTCCTTGAGACAGGTTGAGTGCGCCTGCTAACAGAGCAAATTCGAACGAAAGTGATGTACCTAAATGGAGATTGTAGGGACACTTCGCCTTACCCGTAATATCACCTGTGGTCGTCGTAGACCAGGTCAGTCGTTGCTGGAGCTTCCAGAGTACGGTGTCCCTGTCTGAGCGTACGGTCGACCTGAAGCCTGGATTTGATAATGCCATACTATTACTGTTCCGTCAATTCGACGGTTCCCCCCTATCCCTACAACATGAAACATCAGACCCAGAATGCCTCTATCTCAATTTAACTCCGCTCTAACCTTTACCCGCTCGTTAACTCATGCACGAGTTGGACAATCGGGGCACGAGGGTAGCTGCTGACTTCAGGCCCGTACATGTCGCCGAAACGTCCAAGCC")

print(As, Cs, Gs, Ts)
