def reverse(string):
    if len(string) == 0:
        return string
    else:
        return reverse(string[1:]) + string[0]


def complement(string):
    new_string = ''
    for n in string:
        if n == 'A':
            new_string = new_string + 'T'
        elif n == 'T':
            new_string = new_string + 'A'
        elif n == 'C':
            new_string = new_string + 'G'
        elif n == 'G':
            new_string = new_string + 'C'
    return new_string

c_string = complement(reverse(
"CATCTATCTCGATATGCCAGCCGCGCCCGGAAGAACAGTAAGGCATAGAACAGCCAACCTATTCATCGAGATGCGACTTGCATTTTTACATACGCTCCTCAGACGCCTCCCGCGCCCCTCGGTCGAGTCCTGGAATTGGTTTAAACTTCGGCAATCAAAGGAACACACCGACTTAAGCGTCTTAGTGACCCGTTTATAGATTCAAAGTGTGAGCTGGTGAGGACATTTCCTGTCGAATACAGCTGGATTTCGTGTACCTGAAAATCTCTTTACATTAACAATCTGCATACGATCCACCGCAAAAAGATCGATCGGGGGATGATACGTCTATATAACTGCGATACAAATGGCGTTGACGAGTACACGATGGGTTAAGGCACAGTCCTCGTCATGTGGTGCGTCCGCCCGCTTCGCTGTTCTATACTGCCATCCGTCTTTTGACATACCTTGGCGATCATCATGGTGCTCTGTCGAATCTCAGCCCCGAAGATCAGCTTTCATTACCAGAAAAGACCAGAAATTCTTACGAAGTGGATTAGGCAACTGAACAACCCTAGGGGCCACAGTTCTTCGATACTGACTGCGCCGAACCCCCAGAAGCATTCCCGGAAAAGTAAAACGTGGCAGAGACAGGGTACTGTGGCTAATGTAAACCTTTGTTGCACAGGTTAAAAACTACTGTCAGAGTGACCTGCGCTTAACGTATTAGCGGCCCTTTCCGACGGTGTGAAGGAAGTCACCAATTCGTCTCGCACCGTTATTAGCGTTTGATGAGCTAAAATCTGACAGTCCGTGTCCGGTACTGGATAACCGCTTATTTGGTAGGTGGCAATGGGTTACCTTGCAATTAGTTGGCCCGTTGCATCAGAAGCACCTAAGTTTATGCTGAAGTGGAATGCTCACACGGCGACTAGGGCCAGGGGAGAGCCGTTCCTTACTCGGAGTG"

))

print(c_string)
